import type { Metadata } from "next";
import "./globals.css";
import MianContext from "@/components/MianContext/MianContext";
import Navbar from "@/components/Navbar/page";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className=" overflow-x-hidden bg-linear-to-br from-blue-950 via-blue-800 to-purple-950 min-h-screen" >
        <MianContext>
          <Navbar />  
          {children}
          
        </MianContext>
      </body>
    </html>
  );
}
